### PR TITLE
FISH-6976: upgrading microprofile metrics to 5

### PR DESCRIPTION
**Pull request by breakponchito**
This is to upgrade the metrics tck to 5

after excluding the optional test for Rest.request we have the following results:
`
[INFO] Tests run: 147, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- maven-failsafe-plugin:3.0.0-M5:verify (verify) @ metrics-tck ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
`

### CODE REVIEW

**Comment by Pandrex247** [comment]
We **may** need to consider the optional tests.

**Review by Pandrex247 — CHANGES_REQUESTED** [review]
After a discussion, we should be running the optional base metric tests

**Comment by breakponchito** [comment]
I already added the optional base metric test and also I excluded the MpMetricOptionalTest related to the Rest.request test that we don't need

**Review by luiseufrasio — APPROVED** [review]
LGTM!

**Review by Pandrex247 — COMMENTED** [review]
_payara-micro-managed_ profile seems to fail. Seems to work against Payara Server full and web though.

`mvn clean verify -Dpayara.version=6.2023.1-SNAPSHOT -Ppayara-micro-managed -Dmicro.randomPort=false`

```
[ERROR] Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 7.675 s <<< FAILURE! - in org.eclipse.microprofile.metrics.test.optional.MPMetricBaseMetricsTest
[ERROR] org.eclipse.microprofile.metrics.test.optional.MPMetricBaseMetricsTest.testGcTimeMetrics  Time elapsed: 0.016 s  <<< FAILURE!
java.lang.AssertionError: Line format should be gc_time_seconds_total\{.*?\} \d+\.\d+
        at org.eclipse.microprofile.metrics.test.optional.MPMetricBaseMetricsTest.testGcTimeMetrics(MPMetricBaseMetricsTest.java:316)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   MPMetricBaseMetricsTest.testGcTimeMetrics:316 Line format should be gc_time_seconds_total\{.*?\} \d+\.\d+
[INFO]
[ERROR] Tests run: 147, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by breakponchito** [comment]
after fixing now the payara-micro-managed profile is passing:
using: mvn clean verify -Dpayara.version=6.2023.1-SNAPSHOT -Ppayara-micro-managed -Dmicro.randomPort=false
`
[INFO] Results:
[INFO]
[INFO] Tests run: 147, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- maven-failsafe-plugin:3.0.0-M5:verify (verify) @ metrics-tck ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
`

**Review by Pandrex247 — APPROVED** [review]

**Pull request merged**
