### PR TITLE
FISH-7126 Latest Arquillian Connector 3-alpha fails with Microprofile TCK

### PR DESCRIPTION
**Pull request by arieki**
## Blocker
https://github.com/payara/ecosystem-arquillian-connectors/pull/217

### CODE REVIEW

**Review by Pandrex247 — CHANGES_REQUESTED** [review]
Breaks OpenAPI running against payara-micro-managed

**Review by Pandrex247 — APPROVED** [review]
Ignore me, retried and it worked

**Comment by Pandrex247** [comment]
It would be appreciated if we held off on merging this until next week when the releases were out the door, rather than updating the test suites as we're trying to certify things 🙂

**Comment by arieki** [comment]
> It would be appreciated if we held off on merging this until next week when the releases were out the door, rather than updating the test suites as we're trying to certify things 🙂

sure, I will put label on this PR

**Pull request merged**
