### PR TITLE
FISH-7293 FISH-7105 Package slf4j-api in test archive to satisfy TestNg 7.5 dependency

### PR DESCRIPTION
**Pull request by arieki**
Upgrade TestNG to `7.5.1` and Arquillian to `1.7.0.Final`

## Test Performed

[MP TCK through Jenkins](https://jenkins.payara.fish/blue/organizations/jenkins/BuildAndRunMPTCKs/detail/BuildAndRunMPTCKs/324/pipeline)

### CODE REVIEW

**Review by Pandrex247 — COMMENTED** [review]
Getting pulled into another task mid-review...

Testing against Community master:
* payara-server-remote profile seems to work
* payara-micro-managed profile gets errors in fault tolerance and config - need to review if this is my environment or not

**Comment by arieki** [comment]
> Getting pulled into another task mid-review...
> 
> Testing against Community master:
> 
> * payara-server-remote profile seems to work
> * payara-micro-managed profile gets errors in fault tolerance and config - need to review if this is my environment or not

I've tested payara-micro-managed profile in my WSL machine, those two failed even against `microprofile-6.0` branch. Seems due to my environment. I need to figure out the other way how to verify payara-micro-managed profile

**Review by Pandrex247 — APPROVED** [review]

**Comment by Pandrex247** [comment]
This is breaking Jenkins.
There appears to be something wrong with the checksum of the arquillian BOM uploaded to Maven Central

```
Could not transfer artifact org.jboss.arquillian:arquillian-bom:pom:1.7.0.Final from/to central (https://repo.maven.apache.org/maven2): Checksum validation failed, expected 2811ba27a71a8bda0602161ffe2f6e1429da8068 but is 36257165a0945753efb3f9d473d86c6f4c6c6f6e
```

**Comment by arieki** [comment]
> This is breaking Jenkins. There appears to be something wrong with the checksum of the arquillian BOM uploaded to Maven Central
> 
> ```
> Could not transfer artifact org.jboss.arquillian:arquillian-bom:pom:1.7.0.Final from/to central (https://repo.maven.apache.org/maven2): Checksum validation failed, expected 2811ba27a71a8bda0602161ffe2f6e1429da8068 but is 36257165a0945753efb3f9d473d86c6f4c6c6f6e
> ```

ouch, interesting. 
probably the artifact cached in jenkins m2 repo? corrupted download? just a guess.

**Comment by Pandrex247** [comment]
It's not a Maven caching issue - if you build using a clean maven repo and with the `--strict-checksums` option you will get the same failure

**Comment by arieki** [comment]
> It's not a Maven caching issue - if you build using a clean maven repo and with the `--strict-checksums` option you will get the same failure

got it, you are right. I just re-visited the [BuildAndRunMPTCKs](https://jenkins.payara.fish/blue/organizations/jenkins/BuildAndRunMPTCKs/detail/BuildAndRunMPTCKs/324/pipeline/55/) that I've run. it throws checksum warning, but since it executed without `--strict-checksums` it ignored the WARNING
```
[WARNING] Checksum validation failed, expected 2811ba27a71a8bda0602161ffe2f6e1429da8068 but is 36257165a0945753efb3f9d473d86c6f4c6c6f6e from central for https://repo.maven.apache.org/maven2/org/jboss/arquillian/arquillian-bom/1.7.0.Final/arquillian-bom-1.7.0.Final.pom
Progress (1): 2.7/11 kB
Progress (1): 5.5/11 kB
Progress (1): 8.2/11 kB
Progress (1): 11/11 kB 
Progress (1): 11 kB   
[WARNING] Could not validate integrity of download from https://repo.maven.apache.org/maven2/org/jboss/arquillian/arquillian-bom/1.7.0.Final/arquillian-bom-1.7.0.Final.pom: Checksum validation failed, expected 2811ba27a71a8bda0602161ffe2f6e1429da8068 but is 36257165a0945753efb3f9d473d86c6f4c6c6f6e
                   
[WARNING] Checksum validation failed, expected 2811ba27a71a8bda0602161ffe2f6e1429da8068 but is 36257165a0945753efb3f9d473d86c6f4c6c6f6e from central for https://repo.maven.apache.org/maven2/org/jboss/arquillian/arquillian-bom/1.7.0.Final/arquillian-bom-1.7.0.Final.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/jboss/arquillian/arquillian-bom/1.7.0.Final/arquillian-bom-1.7.0.Final.pom (11 kB at 14 kB/s)
```
<del>Do you have any advice how to follow up this issue? @Pandrex247</del>
I have raised an issue in https://github.com/arquillian/arquillian-core/issues/488
 
<del>in the meantime, I will try to run the mp tck again in my machine using `--strict-checksums` and see whether I can reproduce it locally</del>
issue reproduced in maven 3.6.3

**Pull request merged**
